# query allSanityPizza {
# allSanityPizza {
#     nodes {
#         ...testFragment
#     }
# }
# }

fragment testFragment on SanityPizza {
    id
    name
    slug {
        current
    }
    toppings {
        id
        name
    }
    image {
        asset {
            id
            fluid(maxWidth: 400) {
                ...GatsbySanityImageFluid
            }
        }
    }
}
